import { Plot, Upgrade, CraftRecipe, Achievement } from '../types';

export const INITIAL_PLOTS: Plot[] = [
  { id: 0, row: 0, col: 0, unlocked: true, unlockCost: 0, tree: { type: 'apple', level: 1, fruitCount: 12, maxFruit: 99, growthProgress: 0 } },
  { id: 1, row: 0, col: 1, unlocked: false, unlockCost: 25, tree: null },
  { id: 2, row: 0, col: 2, unlocked: false, unlockCost: 75, tree: null },
  { id: 3, row: 0, col: 3, unlocked: false, unlockCost: 150, tree: null },
  { id: 4, row: 1, col: 0, unlocked: false, unlockCost: 300, tree: null },
  { id: 5, row: 1, col: 1, unlocked: false, unlockCost: 500, tree: null },
  { id: 6, row: 1, col: 2, unlocked: false, unlockCost: 750, tree: null },
  { id: 7, row: 1, col: 3, unlocked: false, unlockCost: 1000, tree: null },
  { id: 8, row: 2, col: 0, unlocked: false, unlockCost: 1500, tree: null },
  { id: 9, row: 2, col: 1, unlocked: false, unlockCost: 2200, tree: null },
  { id: 10, row: 2, col: 2, unlocked: false, unlockCost: 3000, tree: null },
  { id: 11, row: 2, col: 3, unlocked: false, unlockCost: 4000, tree: null },
  { id: 12, row: 3, col: 0, unlocked: false, unlockCost: 5500, tree: null },
  { id: 13, row: 3, col: 1, unlocked: false, unlockCost: 7500, tree: null },
  { id: 14, row: 3, col: 2, unlocked: false, unlockCost: 10000, tree: null },
  { id: 15, row: 3, col: 3, unlocked: false, unlockCost: 15000, tree: null },
];

export const UPGRADES: Upgrade[] = [
  {
    id: 'shears',
    name: 'Golden Pruning Shears',
    description: '+10% Critical Harvest chance and +1 bonus fruit per click.',
    level: 0,
    maxLevel: 10,
    cost: 20,
    costMultiplier: 1.8,
  },
  {
    id: 'basket',
    name: 'Woven Deep Bushels',
    description: '+15% selling price for all fruits at the farmer market.',
    level: 0,
    maxLevel: 10,
    cost: 35,
    costMultiplier: 1.7,
  },
  {
    id: 'fertilizer',
    name: 'Compost & Bio-Char',
    description: '+20% tree growth speed across all cultivated plots.',
    level: 0,
    maxLevel: 10,
    cost: 60,
    costMultiplier: 1.9,
  },
  {
    id: 'irrigation',
    name: 'Artisan Drip Irrigation',
    description: '+15 maximum fruit capacity per tree before filling up.',
    level: 0,
    maxLevel: 10,
    cost: 100,
    costMultiplier: 1.8,
  },
  {
    id: 'robin',
    name: 'Farmhand Robin',
    description: 'A tireless helper who harvests ripe fruit automatically every few seconds.',
    level: 0,
    maxLevel: 5,
    cost: 250,
    costMultiplier: 2.2,
  },
  {
    id: 'beatrice',
    name: 'Botanist Beatrice',
    description: 'Orchard botanist providing +25% growth acceleration to all varieties.',
    level: 0,
    maxLevel: 5,
    cost: 500,
    costMultiplier: 2.3,
  },
  {
    id: 'silas',
    name: 'Master Silas & Wagon',
    description: 'Sweeps the entire orchard periodically, harvesting all ripe trees in one go.',
    level: 0,
    maxLevel: 5,
    cost: 1200,
    costMultiplier: 2.5,
  },
];

export const CRAFTING_RECIPES: CraftRecipe[] = [
  // 2-Produce Recipes
  {
    id: 'cider_apple_pear',
    name: 'Orchard Apple-Pear Cider',
    outputName: 'Apple-Pear Cider',
    ingredients: [
      { fruitType: 'apple', amount: 4 },
      { fruitType: 'pear', amount: 4 },
    ],
    bottleValue: 75,
    category: '2-produce',
    description: 'Classic crisp cider blending tart orchard apples with sweet juicy pears.',
  },
  {
    id: 'cherry_berry_splash',
    name: 'Cherry Berry Splash',
    outputName: 'Cherry Berry Splash',
    ingredients: [
      { fruitType: 'cherry', amount: 4 },
      { fruitType: 'berries', amount: 5 },
    ],
    bottleValue: 160,
    category: '2-produce',
    description: 'Vibrant ruby-red cordial with tart cherries and wild brambleberries.',
  },
  {
    id: 'sunrise_peach_citrus',
    name: 'Sunrise Peach-Citrus Quench',
    outputName: 'Peach-Citrus Quench',
    ingredients: [
      { fruitType: 'peaches', amount: 4 },
      { fruitType: 'lemon', amount: 3 },
    ],
    bottleValue: 240,
    category: '2-produce',
    description: 'Sun-drenched summer nectar balancing fragrant peaches with zesty lemon.',
  },
  {
    id: 'sweet_honeycrisp',
    name: 'Honeycrisp Golden Nectar',
    outputName: 'Honeycrisp Nectar',
    ingredients: [
      { fruitType: 'honeycrisp', amount: 3 },
      { fruitType: 'honey', amount: 2 },
    ],
    bottleValue: 400,
    category: '2-produce',
    description: 'Pure cold-pressed Honeycrisp apples infused with golden wildflower honey.',
  },
  {
    id: 'plum_berry_blush',
    name: 'Plum Berry Blush',
    outputName: 'Plum Berry Blush',
    ingredients: [
      { fruitType: 'plum', amount: 4 },
      { fruitType: 'berries', amount: 4 },
    ],
    bottleValue: 180,
    category: '2-produce',
    description: 'Deep velvety blend of ripe purple plums and tart woodland berries.',
  },
  {
    id: 'carrot_apple_zing',
    name: 'Carrot-Apple Morning Zing',
    outputName: 'Carrot-Apple Zing',
    ingredients: [
      { fruitType: 'carrots', amount: 5 },
      { fruitType: 'apple', amount: 4 },
    ],
    bottleValue: 110,
    category: '2-produce',
    description: 'Vibrant orange breakfast tonic packed with crisp sweet apples and crunchy garden carrots.',
  },
  {
    id: 'summer_melon_berry',
    name: 'Summer Melon Berry Fizz',
    outputName: 'Melon Berry Fizz',
    ingredients: [
      { fruitType: 'watermelon', amount: 3 },
      { fruitType: 'berries', amount: 4 },
    ],
    bottleValue: 220,
    category: '2-produce',
    description: 'Crisp and thirst-quenching watermelon paired with sweet crushed berries.',
  },

  // 3-Produce Recipes
  {
    id: 'golden_grove_trio',
    name: 'Golden Grove Trio',
    outputName: 'Golden Grove Trio',
    ingredients: [
      { fruitType: 'honeycrisp', amount: 3 },
      { fruitType: 'pear', amount: 3 },
      { fruitType: 'honey', amount: 2 },
    ],
    bottleValue: 520,
    category: '3-produce',
    description: 'Luxurious golden blend of aromatic Honeycrisp, delicate pears, and rich farmstead honey.',
  },
  {
    id: 'triple_stonefruit',
    name: 'Triple Stonefruit Punch',
    outputName: 'Triple Stonefruit Punch',
    ingredients: [
      { fruitType: 'peaches', amount: 3 },
      { fruitType: 'plum', amount: 3 },
      { fruitType: 'cherry', amount: 4 },
    ],
    bottleValue: 380,
    category: '3-produce',
    description: 'Sumptuous country punch uniting luscious peaches, tart cherries, and dark plums.',
  },
  {
    id: 'farmhouse_vitality',
    name: 'Farmhouse Vitality Tonic',
    outputName: 'Farmhouse Vitality Tonic',
    ingredients: [
      { fruitType: 'carrots', amount: 4 },
      { fruitType: 'apple', amount: 3 },
      { fruitType: 'lemon', amount: 2 },
    ],
    bottleValue: 260,
    category: '3-produce',
    description: 'Bright and zesty wake-up juice with cold-pressed carrots, tart apples, and fresh lemon.',
  },
  {
    id: 'autumn_hearth_cider',
    name: 'Spiced Autumn Hearth Cider',
    outputName: 'Autumn Hearth Cider',
    ingredients: [
      { fruitType: 'pumpkins', amount: 3 },
      { fruitType: 'apple', amount: 4 },
      { fruitType: 'honey', amount: 2 },
    ],
    bottleValue: 450,
    category: '3-produce',
    description: 'Warm, fragrant harvest blend of heirloom pumpkins, crisp apples, and clover honey.',
  },
  {
    id: 'melon_lemonade_sparkler',
    name: 'Melon Lemonade Sparkler',
    outputName: 'Melon Lemonade Sparkler',
    ingredients: [
      { fruitType: 'watermelon', amount: 3 },
      { fruitType: 'lemon', amount: 3 },
      { fruitType: 'honey', amount: 2 },
    ],
    bottleValue: 480,
    category: '3-produce',
    description: 'Sparkling refreshing watermelon and fresh squeezed lemon sweetened with pure honey.',
  },
  {
    id: 'garden_gazpacho',
    name: 'Country Garden Gazpacho Cooler',
    outputName: 'Garden Gazpacho Cooler',
    ingredients: [
      { fruitType: 'tomatoes', amount: 4 },
      { fruitType: 'carrots', amount: 3 },
      { fruitType: 'onions', amount: 2 },
    ],
    bottleValue: 290,
    category: '3-produce',
    description: 'Savory farmstead vegetable juice steeped with vine-ripened tomatoes, sweet carrots, and garden onions.',
  },

  // 4-Produce Recipes
  {
    id: 'royal_orchard_reserve',
    name: 'Royal Four-Fruit Reserve',
    outputName: 'Royal Four-Fruit Reserve',
    ingredients: [
      { fruitType: 'honeycrisp', amount: 3 },
      { fruitType: 'pear', amount: 3 },
      { fruitType: 'peaches', amount: 3 },
      { fruitType: 'honey', amount: 2 },
    ],
    bottleValue: 950,
    category: '4-produce',
    description: 'Exquisite masterwork combining four premier orchard varieties into a royal elixir.',
  },
  {
    id: 'forest_four_fruit',
    name: 'Deep Forest Four-Fruit Elixir',
    outputName: 'Forest Four-Fruit Elixir',
    ingredients: [
      { fruitType: 'apple', amount: 4 },
      { fruitType: 'cherry', amount: 4 },
      { fruitType: 'plum', amount: 3 },
      { fruitType: 'berries', amount: 4 },
    ],
    bottleValue: 540,
    category: '4-produce',
    description: 'Complex dark-fruit nectar combining tart apples, plump cherries, velvet plums, and berries.',
  },
  {
    id: 'harvest_moon_ambrosia',
    name: 'Harvest Moon Ambrosia',
    outputName: 'Harvest Moon Ambrosia',
    ingredients: [
      { fruitType: 'pumpkins', amount: 3 },
      { fruitType: 'honeycrisp', amount: 3 },
      { fruitType: 'carrots', amount: 3 },
      { fruitType: 'honey', amount: 2 },
    ],
    bottleValue: 780,
    category: '4-produce',
    description: 'Opulent autumn blend of sweet pumpkins, crisp Honeycrisp, earthy carrots, and honey.',
  },
  {
    id: 'grand_garden_bounty',
    name: 'Grand Garden Bounty Tonic',
    outputName: 'Grand Garden Bounty Tonic',
    ingredients: [
      { fruitType: 'tomatoes', amount: 3 },
      { fruitType: 'carrots', amount: 3 },
      { fruitType: 'corn', amount: 3 },
      { fruitType: 'lemon', amount: 2 },
    ],
    bottleValue: 460,
    category: '4-produce',
    description: 'Nutrient-rich estate harvest tonic featuring ripe tomatoes, crisp carrots, sweet summer corn, and lemon.',
  },
  {
    id: 'sun_kissed_fruit_medley',
    name: 'Sun-Kissed Fruit Medley',
    outputName: 'Sun-Kissed Fruit Medley',
    ingredients: [
      { fruitType: 'watermelon', amount: 3 },
      { fruitType: 'peaches', amount: 3 },
      { fruitType: 'berries', amount: 3 },
      { fruitType: 'lemon', amount: 2 },
    ],
    bottleValue: 680,
    category: '4-produce',
    description: 'Brilliant burst of thirst-quenching watermelon, velvety peaches, dark berries, and tart lemon.',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_pluck',
    title: 'First Pluck',
    description: 'Harvest your very first fruit from the orchard.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    asciiBadge: '🌱',
  },
  {
    id: 'bushel_full',
    title: 'Bushel Full',
    description: 'Harvest 50 crisp apples.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 50,
    asciiBadge: '🧺',
  },
  {
    id: 'orchard_expansion',
    title: 'Green Acres',
    description: 'Unlock at least 4 orchard plots.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 4,
    asciiBadge: '🚜',
  },
  {
    id: 'cider_presser',
    title: 'Master Presser',
    description: 'Press your first bottle of artisanal beverage in the farmhouse.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    asciiBadge: '🍾',
  },
  {
    id: 'variety_grower',
    title: 'Biodiverse Orchard',
    description: 'Grow at least 3 distinct fruit tree varieties simultaneously.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 3,
    asciiBadge: '🌿',
  },
  {
    id: 'penny_pincher',
    title: 'Orchard Tycoon',
    description: 'Amass a treasury of $1,000 in your farm account.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 1000,
    asciiBadge: '💰',
  },
  {
    id: 'grand_estate',
    title: 'Grand Estate',
    description: 'Clear and unlock all 16 orchard plots.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 16,
    asciiBadge: '🏰',
  },
  {
    id: 'thousand_fruits',
    title: 'Thousand Fruit Harvest',
    description: 'Harvest a total of 1,000 fruits throughout your farming career.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 1000,
    asciiBadge: '👑',
  },
];
