import { Plot, Upgrade, CraftRecipe, Achievement } from '../types';

export const INITIAL_PLOTS: Plot[] = [
  { id: 0, row: 0, col: 0, unlocked: true, unlockCost: 0, tree: { type: 'apple', level: 1, fruitCount: 12, maxFruit: 99, growthProgress: 0 } },
  { id: 1, row: 0, col: 1, unlocked: false, unlockCost: 25, tree: null },
  { id: 2, row: 0, col: 2, unlocked: false, unlockCost: 75, tree: null },
  { id: 3, row: 0, col: 3, unlocked: false, unlockCost: 150, tree: null },
  { id: 4, row: 1, col: 0, unlocked: false, unlockCost: 300, tree: null },
  { id: 5, row: 1, col: 1, unlocked: false, unlockCost: 500, tree: null },
  { id: 6, row: 1, col: 2, unlocked: false, unlockCost: 750, tree: null },
  { id: 7, row: 1, col: 3, unlocked: false, unlockCost: 1000, tree: null },
  { id: 8, row: 2, col: 0, unlocked: false, unlockCost: 1500, tree: null },
  { id: 9, row: 2, col: 1, unlocked: false, unlockCost: 2200, tree: null },
  { id: 10, row: 2, col: 2, unlocked: false, unlockCost: 3000, tree: null },
  { id: 11, row: 2, col: 3, unlocked: false, unlockCost: 4000, tree: null },
  { id: 12, row: 3, col: 0, unlocked: false, unlockCost: 5500, tree: null },
  { id: 13, row: 3, col: 1, unlocked: false, unlockCost: 7500, tree: null },
  { id: 14, row: 3, col: 2, unlocked: false, unlockCost: 10000, tree: null },
  { id: 15, row: 3, col: 3, unlocked: false, unlockCost: 15000, tree: null },
];

export const UPGRADES: Upgrade[] = [
  {
    id: 'shears',
    name: 'Golden Pruning Shears',
    description: '+10% Critical Harvest chance and +1 bonus fruit per click.',
    level: 0,
    maxLevel: 10,
    cost: 20,
    costMultiplier: 1.8,
  },
  {
    id: 'basket',
    name: 'Woven Deep Bushels',
    description: '+15% selling price for all fruits at the farmer market.',
    level: 0,
    maxLevel: 10,
    cost: 35,
    costMultiplier: 1.7,
  },
  {
    id: 'fertilizer',
    name: 'Compost & Bio-Char',
    description: '+20% tree growth speed across all cultivated plots.',
    level: 0,
    maxLevel: 10,
    cost: 60,
    costMultiplier: 1.9,
  },
  {
    id: 'irrigation',
    name: 'Artisan Drip Irrigation',
    description: '+15 maximum fruit capacity per tree before filling up.',
    level: 0,
    maxLevel: 10,
    cost: 100,
    costMultiplier: 1.8,
  },
  {
    id: 'robin',
    name: 'Farmhand Robin',
    description: 'A tireless helper who harvests ripe fruit automatically every few seconds.',
    level: 0,
    maxLevel: 5,
    cost: 250,
    costMultiplier: 2.2,
  },
  {
    id: 'beatrice',
    name: 'Botanist Beatrice',
    description: 'Orchard botanist providing +25% growth acceleration to all varieties.',
    level: 0,
    maxLevel: 5,
    cost: 500,
    costMultiplier: 2.3,
  },
  {
    id: 'silas',
    name: 'Master Silas & Wagon',
    description: 'Sweeps the entire orchard periodically, harvesting all ripe trees in one go.',
    level: 0,
    maxLevel: 5,
    cost: 1200,
    costMultiplier: 2.5,
  },
];

export const CRAFTING_RECIPES: CraftRecipe[] = [
  {
    id: 'cider_apple',
    name: 'Artisan Sweet Apple Cider',
    outputName: 'Apple Cider',
    fruitType: 'apple',
    fruitRequired: 10,
    bottleValue: 35,
    description: 'Freshly pressed cloudy cider with cinnamon and autumn spice.',
  },
  {
    id: 'perry_pear',
    name: 'Sparkling Pear Perry',
    outputName: 'Pear Perry',
    fruitType: 'pear',
    fruitRequired: 8,
    bottleValue: 90,
    description: 'Effervescent and delicate nectar fermented to golden perfection.',
  },
  {
    id: 'liqueur_cherry',
    name: 'Kirsch Cherry Cordial',
    outputName: 'Cherry Cordial',
    fruitType: 'cherry',
    fruitRequired: 8,
    bottleValue: 180,
    description: 'Velvety deep ruby aperitif aged in charred oak casks.',
  },
  {
    id: 'brandy_plum',
    name: 'Old Plum Slivovitz Brandy',
    outputName: 'Plum Brandy',
    fruitType: 'plum',
    fruitRequired: 6,
    bottleValue: 320,
    description: 'Traditional potent spirit distilled with complex plum essence.',
  },
  {
    id: 'limoncello_lemon',
    name: 'Sun-Drenched Limoncello',
    outputName: 'Limoncello',
    fruitType: 'lemon',
    fruitRequired: 5,
    bottleValue: 550,
    description: 'Zesty lemon peel steeped with pure sugar cane elixir.',
  },
  {
    id: 'reserve_honeycrisp',
    name: 'Grand Cru Honeycrisp Reserve',
    outputName: 'Honeycrisp Reserve',
    fruitType: 'honeycrisp',
    fruitRequired: 5,
    bottleValue: 1200,
    description: 'Award-winning estate reserve bottle sought by royal connoisseurs.',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_pluck',
    title: 'First Pluck',
    description: 'Harvest your very first fruit from the orchard.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    asciiBadge: '🌱',
  },
  {
    id: 'bushel_full',
    title: 'Bushel Full',
    description: 'Harvest 50 crisp apples.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 50,
    asciiBadge: '🧺',
  },
  {
    id: 'orchard_expansion',
    title: 'Green Acres',
    description: 'Unlock at least 4 orchard plots.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 4,
    asciiBadge: '🚜',
  },
  {
    id: 'cider_presser',
    title: 'Master Presser',
    description: 'Press your first bottle of artisanal beverage in the farmhouse.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    asciiBadge: '🍾',
  },
  {
    id: 'variety_grower',
    title: 'Biodiverse Orchard',
    description: 'Grow at least 3 distinct fruit tree varieties simultaneously.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 3,
    asciiBadge: '🌿',
  },
  {
    id: 'penny_pincher',
    title: 'Orchard Tycoon',
    description: 'Amass a treasury of $1,000 in your farm account.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 1000,
    asciiBadge: '💰',
  },
  {
    id: 'grand_estate',
    title: 'Grand Estate',
    description: 'Clear and unlock all 16 orchard plots.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 16,
    asciiBadge: '🏰',
  },
  {
    id: 'thousand_fruits',
    title: 'Thousand Fruit Harvest',
    description: 'Harvest a total of 1,000 fruits throughout your farming career.',
    rewardMoney: 0,
    unlocked: false,
    progress: 0,
    maxProgress: 1000,
    asciiBadge: '👑',
  },
];
